# Numpy

For most data analysis applications, the main areas of functionality I’ll focus on are:<br>
• Fast array-based operations for data munging and cleaning, subsetting and filter‐
ing, transformation, and any other kind of computation<br>
• Common array algorithms like sorting, unique, and set operations<br>
• Efficient descriptive statistics and aggregating/summarizing data<br>
• Data alignment and relational data manipulations for merging and joining heter‐
ogeneous datasets<br>
• Expressing conditional logic as array expressions instead of loops with if-elifelse branches<br>
• Group-wise data manipulations (aggregation, transformation, and function<
application)<br>

In [2]:
import numpy as np

In [3]:
data = np.array([[1.5,-0.1,3],[0,-3,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [4]:
data *10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [5]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

Creating Ndarray

In [8]:
data1 = [1,2,3,4,5,0]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5, 0])

In [9]:
data2 = [[1,2,3,4],[5,6,7,8]] #data2 was a list of lists
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [12]:
arr1.dtype

dtype('int64')

In [13]:
arr2.dtype

dtype('int64')

numpy.zeros and numpy.ones 


In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.empty((2,2,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

It’s not safe to assume that numpy.empty will return an array of all
zeros. This function returns uninitialized memory and thus may
contain nonzero “garbage” values. You should use this function
only if you intend to populate the new array with data.

In [18]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.identity(2,int)

array([[1, 0],
       [0, 1]])

### Data Types for ndarrays

In [20]:
arr = np.array([3.7,-1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [21]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

### Arithmetic with NumPy Arrays


Arrays are important because they enable you to express batch operations on data
without writing any for loops. NumPy users call this **vectorization**.

In [22]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr+arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [24]:
arr-arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
arr*arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [26]:
arr ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [27]:
1 / arr

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [28]:
arr>arr

array([[False, False, False, False],
       [False, False, False, False]])

### Basic indexing and Slicing

In [29]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[5]

np.int64(5)

In [31]:
arr[5:8]

array([5, 6, 7])

In [32]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10])

In [33]:
## Create  SLICER of arr
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [34]:
arr_slice[1]=12345
arr_slice
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9,    10])

In [35]:
## The “bare” slice [:] will assign to all values in an array

arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9, 10])

### Indexing with slices

In [36]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9, 10])

In [37]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [38]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

### Boolen Indexing
You can use conditions to filter elements.

In [40]:
name = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])


In [41]:
name=="Bob"

array([ True, False, False,  True, False, False, False])

In [42]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12,-4],[3,4]])

In [43]:
data[name == "Bob"]

array([[4, 7],
       [0, 0]])

data[name == "Bob"]

In [44]:
name

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [45]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [46]:
data.shape

(7, 2)

In [47]:
data.ndim

2

### Fancy indexing
You can access multiple specific elements using lists or arrays of indices.


In [48]:
arr = np.zeros((8,4)) # 8 by 4
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

To select a subset of the rows in a particular order, you can simply pass a list or
ndarray of integers specifying the desired order:

In [49]:
arr[[2,3,1,7]]

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

In [50]:
arr[[-7,-6,-5]]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

### Transposing Arrays and Swapping Axes

In [51]:
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [52]:
arr = np.array([
    [0, 1, 0],
    [1, 2, -2],
    [6, 3, 2],
    [-1, 0, -1],
    [1, 0, 1]
])

result = arr.T @ arr
print(result)


[[39 20 12]
 [20 14  2]
 [12  2 10]]


In [53]:
arr.swapaxes(0, 1)


array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])